### ISSUE TITLE
(SproutPro) (MV) Search for SKU in Line Items

### ISSUE THREAD

**Issue by elanasparkle** [SproutApps/sprout-invoices#63]
Ability to search for SKU in both Line items and WooCommerce line items.

**Comment by elanasparkle** [comment]
Having the ability to search from the SKU from a WooCommerce Product

![image](https://user-images.githubusercontent.com/5271694/125941628-f36d0118-0456-4944-87fd-bb354bca5560.png)

Providing the ability to search for that item in Line times in the Woo Products. 

![image](https://user-images.githubusercontent.com/5271694/125941772-f036ffb4-3800-4c41-8fd5-505ddb5a315f.png)

We are getting the data on the product_data array but searching on that would help out customers that rely on the SKU. This is something that customers with a lot of products lean on and the si_woo_products.js only searches on the name.

**Comment by dancameron** [comment]
There are a couple of ways to accommodate this:

1. ~~Hide the sku inside a data attribute that select2 would find.~~ This isn't as easy as I thought, since select2 doesn't search data attributes on the option elem. A custom search field could be created but the complexity of this solution is a lot more than...
2. Add the SKU (if available) to the name of the option. For example, instead of "Blue Product Item" it would be "Blue Product Item - SKU: ABC456". Select2 will automatically see the SKU and it will return, just like if they're searching for a product name.

We could also make this change as a code snippet, or as an update for everyone.

**Comment by elanasparkle** [comment]
Moving to pro Sprout Invoices repository.
